### ISSUE TITLE
Flaky test(s): TestConcurrentContextAccess, TestHTTPTransport, TestSpanFinishConcurrentlyWithoutRaces

### ISSUE THREAD

**Issue by tonyo** [getsentry/sentry-go#662]
Platform: Windows
Go version: 1.18

Affected job: https://github.com/getsentry/sentry-go/actions/runs/5456471664/jobs/9929324156

It's not entirely clear from the log yet which test specifically is causing the 5 minute timeout, but one of `TestConcurrentContextAccess`, `TestHTTPTransport`, `TestSpanFinishConcurrentlyWithoutRaces` seems to be the problem.

<details>
<summary>Test log</summary>

```
  make test
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GO111MODULE: on
    GOFLAGS: -mod=readonly
>>> Running tests for module: .
(cd . && go test -count=1 -timeout 300s  ./...)
panic: test timed out after 5m0s

goroutine 399 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc000150820, {0x130864d?, 0xe3cbd3?}, 0x1346ba0)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc000150820?)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc000150820, 0xc000107cd8)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0001ae460?, {0x16a7780, 0xde, 0xde}, {0x139cb3b0108?, 0x40?, 0x16ac9a0?})
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0001ae460)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:505 +0x1aa

goroutine 938 [chan receive, 4 minutes]:
testing.(*T).Run(0xc0003a89c0, {0x130bb42?, 0x0?}, 0xc0000f2438)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
github.com/getsentry/sentry-go.TestHTTPTransport(0xc0003a84e0?)
	D:/a/sentry-go/sentry-go/transport_test.go:416 +0x4a5
testing.tRunner(0xc0003a89c0, 0x1346ba0)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f

goroutine 144 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000254850)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 151 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000254c40)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 149 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000254af0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 145 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002549a0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 153 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000254d90)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 155 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000254ee0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 157 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255030)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 159 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255180)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 161 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002552d0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 163 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255420)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 165 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255570)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 166 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002556c0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 168 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255810)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 170 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255960)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 171 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255ab0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 173 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255c00)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 175 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255d50)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 177 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc000255ea0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 180 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac000)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 182 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac150)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 184 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac2a0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 186 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac3f0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 188 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac540)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 190 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac690)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 193 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac7e0)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 195 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002ac930)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	D:/a/sentry-go/sentry-go/transport.go:291 +0x5a

goroutine 197 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0002aca80)
	D:/a/sentry-go/sentry-go/transport.go:423 +0x12f

goroutine 925 [runnable]:
github.com/getsentry/sentry-go.TestSpanFinishConcurrentlyWithoutRaces.func2()
	D:/a/sentry-go/sentry-go/tracing_test.go:1000 +0x1d
created by github.com/getsentry/sentry-go.TestSpanFinishConcurrentlyWithoutRaces
	D:/a/sentry-go/sentry-go/tracing_test.go:1000 +0xff

goroutine 924 [runnable]:
github.com/getsentry/sentry-go.(*Span).Finish(...)
	D:/a/sentry-go/sentry-go/tracing.go:234
github.com/getsentry/sentry-go.TestSpanFinishConcurrentlyWithoutRaces.func1()
	D:/a/sentry-go/sentry-go/tracing_test.go:996 +0x1f
created by github.com/getsentry/sentry-go.TestSpanFinishConcurrentlyWithoutRaces
	D:/a/sentry-go/sentry-go/tracing_test.go:994 +0xbc

goroutine 718 [chan receive, 4 minutes]:
github.com/getsentry/sentry-go.TestConcurrentContextAccess.func2()
	D:/a/sentry-go/sentry-go/tracing_test.go:924 +0x49
created by github.com/getsentry/sentry-go.TestConcurrentContextAccess
	D:/a/sentry-go/sentry-go/tracing_test.go:923 +0x1ea
FAIL	github.com/getsentry/sentry-go	300.206s
?   	github.com/getsentry/sentry-go/echo	[no test files]
ok  	github.com/getsentry/sentry-go/fasthttp	0.029s
ok  	github.com/getsentry/sentry-go/gin	1.721s
ok  	github.com/getsentry/sentry-go/http	0.296s
?   	github.com/getsentry/sentry-go/internal/debug	[no test files]
ok  	github.com/getsentry/sentry-go/internal/otel/baggage	0.402s
?   	github.com/getsentry/sentry-go/internal/otel/baggage/internal/baggage	[no test files]
ok  	github.com/getsentry/sentry-go/internal/ratelimit	0.614s
?   	github.com/getsentry/sentry-go/internal/testutils	[no test files]
ok  	github.com/getsentry/sentry-go/internal/traceparser	0.400s
?   	github.com/getsentry/sentry-go/iris	[no test files]
ok  	github.com/getsentry/sentry-go/logrus	0.326s
?   	github.com/getsentry/sentry-go/martini	[no test files]
?   	github.com/getsentry/sentry-go/negroni	[no test files]
FAIL
mingw32-make: *** [makefile:33: test/.] Error 1
```
</details>

**Comment by cleptric** [comment]
Fixed in #682
